dial4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('employees.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'employees'

urlpatterns = [
    url(r'^$', views.index_view, name='home'),
    url(r'^about/', views.about_view, name='about'),
    url(r'^gallery/', views.gallery_view, name='gallery'),
    url(r'^contacts/', views.contact_view, name='contacts'),
    url(r'^employees/', views.employee_view, name='employees'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/models.py
from django.db import models


class EmployeeDetails(models.Model):
    emp_name = models.CharField(default="Employee name", max_length=200)
    emp_title = models.CharField(default="Title",max_length=100)
    emp_bio = models.TextField(default="I love the agency")
    emp_image = models.ImageField(upload_to='Images/', default='Img.jpg')

employees/views.py
from django.shortcuts import render

from .models import EmployeeDetails


def index_view(request):
    details = EmployeeDetails.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Employees/index.html", context)


def about_view(request):
    details = EmployeeDetails.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Employees/about.html",context)


def gallery_view(request):
    details = EmployeeDetails.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Employees/gallery.html", context)


def contact_view(request):
    details = EmployeeDetails.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Employees/contact.html", context)


def employee_view(request):
    details = EmployeeDetails.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Employees/profiles.html", context)

employees/templates/Employees/about.html
{% extends 'Employees/base_layout.html' %}
{%  load static from staticfiles %}

{% block content %}
<!-- banner -->
	<div class="banner1">
		<div class="container">
            {% include 'Employees/navbar.html' %}
		</div>
	</div>
<!-- //banner -->
<!-- about-top -->
<div class="agileits-about-top">
    <div class="container">
        <h3 class="w3ls_head"><span>Who </span>we are </h3>
        <p class="w3agile">Dial a house manager is a small - aiming to be medium and eventually large - corporate that opened its doors in October 2014. It was started by two friends and business partners who have a wealth of experience in hospitality, counseling (psychology), customer care and people management.</p>
        <p class="w3agile">We, the founders of Dial for a House Manager, too have gone through the “drama” of sending money with no show, the lack of respect, lack of professionalism and not forgetting the negligence and damages that happened at home among others. In addition to this, we understand that most of the employers at home are professionals who are exposed to high standards and are results-driven at their work environment and just by default expect the same of their house managers. We also have understood that you and I, who are occupied by our day to day businesses, do not have time to trains, orient and coach a house manager. Thus, the need for Dial for a House Manager.</p>
        <h4 class="w3ls_head"><span>Impact and who </span> our clients are:</h4>
        <p class="w3agile">So far, we have trained over 500 nannies and house managers from different parts of the world, and by default, exposing them to personal hygiene, financial management and savings, how to take advantage of NHIF and NSSF. We have trained them on the core job which is home management and child caring. We guarantee that you will see a difference with our employees.</p>
        <p class="w3agile">Our clients are high and medium end customers who believe in the value for their money.</p>
        <div class="agileinfo-top-grids">
            <div class="col-md-push-2 col-sm-4 wthree-top-grid">
                <h4>Our Vision </h4>
                <p>To be the ultimate house management, home care and hospitality services provider in Kenya and beyond.</p>
            </div>
            <div class="col-md-push-2 col-sm-4 wthree-top-grid">
                <h4>Mission Statement</h4>
                <p>To equip current and potential house helps into professional and self reliant house managers and nannies, teach them to be professional and trust worthy.</p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //about-top -->
	<!-- services -->
	<section class="services" id="courses">
		<div class="container">
			<h2 class="w3ls_head"><span>Training </span>Programs</h2>
			<p class="w3agile">To maintain the high skill level of the house managers, we train them on the followig house management and life skills.</p>
			<div class="wthree-services-grids">
				<div class="col-sm-3 wthree-services">
					<div class="wthree-services-grid">
						<div class="wthree-services-info">
							<i class="fa fa-comment-o" aria-hidden="true"></i>
							<h4>Communication skills</h4>
							<div class="w3ls-border"> </div>
						</div>
						<div class="wthree-services-captn">
							<ul>
                                <li>Telephone skills</li>
                                <li>Communication techniques</li>
                                <li>Communication and ethics</li>
                            </ul>
						</div>
					</div>
				</div>
				<div class="col-sm-3 wthree-services">
					<div class="wthree-services-grid">
						<div class="wthree-services-info">
							<i class="fa fa-edit" aria-hidden="true"></i>
							<h4>Organisation</h4>
							<div class="w3ls-border"> </div>
						</div>
						<div class="wthree-services-captn">
							<ul>
                                <li>Scheduling of duties</li>
                                <li>Shopping list compilation</li>
                            </ul>
						</div>
					</div>
				</div>
				<div class="col-sm-3 wthree-services">
					<div class="wthree-services-grid">
						<div class="wthree-services-info">
							<i class="fa fa-heart" aria-hidden="true"></i>
							<h4>Specialized Care</h4>
							<div class="w3ls-border"> </div>
						</div>
						<div class="wthree-services-captn">
							<ul>
                                <li>First aid & CPR</li>
                                <li>HIV/AIDS awareness</li>
                                <li>Home (frail) care</li>
                            </ul>
						</div>
					</div>
				</div>
				<div class="col-sm-3 wthree-services">
					<div class="wthree-services-grid">
						<div class="wthree-services-info">
							<i class="fa fa-home" aria-hidden="true"></i>
							<h4>Household duties</h4>
							<div class="w3ls-border"> </div>
						</div>
						<div class="wthree-services-captn">
							<ul>
                                <li>Cleaning</li>
                                <li>Table and tray setting</li>
                                <li>Food preparation</li>
                                <li>Garment care</li>
                                <li>Home & personal safety and security</li>
                            </ul>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</section>
	<!-- //services -->
{% endblock %}

employees/templates/Employees/base_layout.html
{% load  staticfiles %}
{% load cloudinary %}

<!--
author: weib solutions
author URL: http://weibsolutions.com
-->
<!DOCTYPE html>
<html lang="en">
<head>
<title>Dial4HM</title>
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
<link href="{% static 'Employees/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'Employees/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'Employees/css/flexslider.css' %}" type="text/css" media="screen" property="" />
<link rel="stylesheet" href="{% static 'Employees/css/custom.css' %}" type="text/css" media="screen" property="" />
<!-- js -->
<script type="text/javascript" src="{% static 'Employees/js/jquery-2.1.4.min.js' %}"></script>
<!-- //js -->
<!-- font-awesome-icons -->
<link rel="stylesheet" href="{% static 'Employees/css/font-awesome.min.css' %}" />
<!-- //font-awesome-icons -->
<link href="//fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i&amp;subset=cyrillic,latin-ext" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
</head>

<body>

    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <!-- footer-->
    <div class="footer" style="color: #000000;">
    <div class="container">
        <div class="w3_agile_footer_grids">
            <!--
            <div class="col-md-4 w3_agile_footer_grid">
                <h3>Latest Tweets</h3>
                <ul class="agile_footer_grid_list">
                    <li><i class="fa fa-twitter" aria-hidden="true"></i>Nam libero tempore, cum soluta nobis est eligendi optio
                        cumque nihil impedit. <span>1 day ago</span></li>
                    <li><i class="fa fa-twitter" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus <a href="mailto:info@mail.com">info@mail.com</a>
                        cumque nihil impedit. <span>2 days ago</span></li>
                </ul>
            </div> -->
            <!--
            <div class="col-md-4 w3_agile_footer_grid">
                <h3>Navigation</h3>
                <ul class="agileits_w3layouts_footer_grid_list">
                    <li><i class="fa fa-angle-double-right" aria-hidden="true"></i><a href="index.html">Home</a></li>
                    <li><i class="fa fa-angle-double-right" aria-hidden="true"></i><a href="about.html">About</a></li>
                    <li><i class="fa fa-angle-double-right" aria-hidden="true"></i><a href="contact.html">Contact</a></li>
                </ul>
            </div>
            -->
            <!--
            <div class="col-md-4 w3_agile_footer_grid">
                <h3>Instagram Posts</h3>
                <div class="w3_agileits_footer_grid_left">
                    <a href="#"><img src="images/s6.jpg" alt=" " class="img-responsive" /></a>
                </div>
                <div class="w3_agileits_footer_grid_left">
                    <a href="#"><img src="images/s2.jpg" alt=" " class="img-responsive" /></a>
                </div>
                <div class="w3_agileits_footer_grid_left">
                    <a href="#"><img src="images/s1.jpg" alt=" " class="img-responsive" /></a>
                </div>
                <div class="w3_agileits_footer_grid_left">
                    <a href="#"><img src="images/s3.jpg" alt=" " class="img-responsive" /></a>
                </div>
                <div class="w3_agileits_footer_grid_left">
                    <a href="#"><img src="images/s4.jpg" alt=" " class="img-responsive" /></a>
                </div>
                <div class="w3_agileits_footer_grid_left">
                    <a href="#"><img src="images/s5.jpg" alt=" " class="img-responsive" /></a>
                </div>
                <div class="clearfix"> </div>
            </div> -->
            <div class="clearfix"> </div>
        </div> <!--
        <div class="w3_newsletter_footer_grids">
            <div class="w3_newsletter_footer_grid_left">
                <form action="#" method="post">
                    <input type="email" name="Email" placeholder="Email" required="">
                    <input type="submit" value="Send">
                </form>
            </div>
        </div> -->
        <div class="w3ls_address_mail_footer_grids">
            <div class="col-md-4 w3ls_footer_grid_left">
                <div class="wthree_footer_grid_left">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                </div>
                <p>Suna Apartments, Suna Road, <span>off Naivasha Rd, Nairobi.</span></p>
            </div>
            <div class="col-md-4 w3ls_footer_grid_left">
                <div class="wthree_footer_grid_left">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                </div>
                <p><a href="tel:+254714379466">+(254) 714 379 466</a> <span><a href="tel:+254702658482">+(254) 702 658 482</a></span> <span><a
                                href="tel:+254720990084">+(254) 720 990 084 </a></span></p>
            </div>
            <div class="col-md-4 w3ls_footer_grid_left">
                <div class="wthree_footer_grid_left">
                    <i class="fa fa-envelope-o" aria-hidden="true"></i>
                </div>
                <p><a href="mailto:4housemanager@gmail.com">4housemanager@gmail.com</a>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="agileinfo_copyright">
            <p>&copy; copyright <!-- <?php print date("Y");?> --> Dial for a House Manager.<br> All Rights Reserved <br> Design by <a href="https://weibsolutions.com/">Weib</a></p>
        </div>
    </div>
</div>
    <!-- //footer-->

	<script type="text/javascript" src="{% static 'Employees/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'Employees/js/easing.js' %}"></script>
	<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
	</script>
<!-- //here ends scrolling icon -->

<!-- for bootstrap working -->
	<script src="{% static 'Employees/js/bootstrap.js' %}"></script>
<!-- //for bootstrap working -->
<!-- carousal -->
	<script src="{% static 'Employees/js/slick.js' %}" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript">
		$(document).on('ready', function() {
		  $(".center").slick({
			dots: true,
			infinite: true,
			centerMode: true,
			slidesToShow: 2,
			slidesToScroll: 2,
			responsive: [
				{
				  breakpoint: 768,
				  settings: {
					arrows: true,
					centerMode: false,
					slidesToShow: 2
				  }
				},
				{
				  breakpoint: 480,
				  settings: {
					arrows: true,
					centerMode: false,
					centerPadding: '40px',
					slidesToShow: 1
				  }
				}
			 ]
		  });
		});
	</script>
<!-- //carousal -->
<!-- gauge-meter -->
	<script src="{% static 'Employees/js/jquery.gauge.js' %}"></script>
	<script>
		$(document).ready(function (){
			$("#gauge1").gauge(30,{color: "#fb5710",unit: " %",type: "halfcircle"});
			$("#gauge2").gauge(70, {color: "#a821e7", unit: " %",type: "halfcircle"});
			$("#gauge3").gauge(75, {color: "#fbb810",unit: " %",type: "halfcircle"});
			$("#gauge4").gauge(90, {color: "#21d0e7",unit: " %",type: "halfcircle"});
		});
	</script>
<!-- //gauge-meter -->

</body>
</html>

employees/templates/Employees/index.html
{% extends 'Employees/base_layout.html' %}
{% load staticfiles %}
{% load cloudinary %}

{% block content %}
<!-- banner -->
	<div class="banner">
        <div>
            {% include 'Employees/navbar.html' %}
        </div>
		<div class="container">
			<div class="w3_agile_banner_info">
				<section class="slider">
						<div class="flexslider">
							<ul class="slides">
								<li>
									<div class="agileits_w3layouts_banner_info">
										<p>The ultimate home hospitality providers in<br> Kenya and beyond</p>
										<h3></h3>
									</div>
								</li>
                                <li>
                                    <div class="agileits_w3layouts_banner_info">
                                        <p>Sharpen your skills</p>
                                        <a href="about.html"><h3>Take our course today</h3></a><!-- link to info on course -->
                                    </div>
                                </li>
								<li>
									<div class="agileits_w3layouts_banner_info">
                                        <p>Interested in a qualified house manager?</p>
                                        <a href="#"><h3>Hire a house manager</h3></a><!-- link to how to hire a house manager -->
									</div>
								</li>
								<li>
									<div class="agileits_w3layouts_banner_info">
                                        <p>Looking for more info?</p>
                                        <a href="about.html"><h3>Learn more</h3></a><!-- link to more info -->
									</div>
								</li>
							</ul>
						</div>
				</section>
			<!-- flexSlider -->
				<script defer src="{% static 'Employees/js/jquery.flexslider.js' %}"></script>
				<script type="text/javascript">
					$(window).load(function(){
					  $('.flexslider').flexslider({
						animation: "slide",
						start: function(slider){
						  $('body').removeClass('loading');
						}
					  });
					});
				</script>
			<!-- //flexSlider -->
				
			</div>
			<div class="agile_banner_social">
				<ul class="agileits_social_list">
					<li><a href="https://www.facebook.com/Dial4HM/" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li> <!--
					<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
					<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
					<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li> -->
				</ul>
			</div>
		</div>
	</div>
<!-- //banner -->	
<!-- banner-bottom -->
	<div class="banner-bottom">
		<div class="container">
		<h2 class="w3ls_head"><span>Wel</span>come</h2>
			<p class="w3agile">Dial for a house manager is an academy that exists with a mission to make the professional woman's life more comfortable by training and providing the professional House Manager and Nannies.</p>
			<div class="wel-ind">
				<div class="col-md-6 agileits_banner_bottom_right">
					<div class="w3ls_banner_bottom_right">
						<img src="{% static 'Employees/images/dhm12.jpg' %}" alt="Dial4HM" height="400" width="400" class="img-responsive" />
						<div class="w3ls_banner_bottom_right_pos">
							<img src="{%  static 'Employees/images/dhm13.jpg' %}" alt="Dial4HM" height="576" width="576" class="img-responsive" />
						</div>
					</div>
				</div>
				<div class="col-md-6 agileits_banner_bottom_left">
				<h4>Experience</h4>
				<p>What makes us the ultimate destination for qualified house managers; whether you're looking to recruit one or seekimg to sharpen your skills.</p>
					<div class="w3l_social_icons">
						<div class="w3l_social_icon_grid">
							<div class="w3l_social_icon_gridl w3_facebook">
								<a href="#">
									<i class="fa fa-clock-o" aria-hidden="true"></i>
								</a>
							</div>
							<div class="w3l_social_icon_gridr">
								<h5 class="counter">5</h5>
							</div>
							<div class="clearfix"> </div>
							<div class="w3l_social_icon_grid_pos">
								<label>-</label>
							</div>
						</div>
						<div class="w3l_social_icon_grid w3ls_social_icon_grid">
							<div class="w3l_social_icon_gridl w3_dribbble">
								<a href="#">
									<i class="fa fa-users" aria-hidden="true"></i>
								</a>
							</div>
							<div class="w3l_social_icon_gridr">
								<h5 class="counter">500</h5>
							</div>
							<div class="clearfix"> </div>
							<div class="w3l_social_icon_grid_pos">
								<label>-</label>
							</div>
						</div>
						<div class="w3l_social_icon_grid">
							<div class="w3l_social_icon_gridl w3_instagram">
								<a href="#">
									<i class="fa fa-tasks" aria-hidden="true"></i>
								</a>
							</div>
							<div class="w3l_social_icon_gridr">
								<h5 class="counter">19</h5>
							</div>
							<div class="clearfix"> </div>
							<div class="w3l_social_icon_grid_pos">
								<label>-</label>
							</div>
						</div>
                        <div class="clearfix"></div>
                        <div>
                            <a href="{% url 'employees:employees' %}" class="btn btn-danger btn-lg">Choose a house manager</a>
                        </div>
					</div>
				</div>
			<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //banner-bottom -->
<!-- Stats -->
	<script src="{% static 'Employees/js/waypoints.min.js' %}"></script>
	<script src="{% static 'Employees/js/counterup.min.js' %}"></script>
	<script>
		jQuery(document).ready(function( $ ) {
			$('.counter').counterUp({
				delay: 10,
				time: 2000
			});
		});
	</script>
<!-- //Stats -->
<!-- skills -->
<!--
	<div class="skills">
		<div class="container">
			<h3 class="w3ls_head"><span>Our </span>Skills</h3>
			<p class="w3agile">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque
				corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
			<div class="w3layouts_skills_grids">
				<div class="col-md-3 w3ls_about_guage">
					<canvas id="gauge1" width="200" height="100"></canvas>
					<h4>Make Money</h4>
				</div>
				<div class="col-md-3 w3ls_about_guage">
					<canvas id="gauge2" width="200" height="100"></canvas>
					<h4>Matching Buyer</h4>
				</div>
				<div class="col-md-3 w3ls_about_guage">
					<canvas id="gauge3" width="200" height="100"></canvas>
					<h4>Market Appraisals</h4>
				</div>
				<div class="col-md-3 w3ls_about_guage">
					<canvas id="gauge4" width="200" height="100"></canvas>
					<h4>Support</h4>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	-->
<!-- //skills -->
<!-- work process -->
	<div class="what-w3ls">
		<div class="container">
			<h3 class="w3ls_head"><span>Work </span>Process</h3>
			<p class="w3agile"></p>
				<div class="what-grids">
					<div class="col-md-6 what-grid">
						<img src="{% static 'Employees/images/d4hm2.jpg' %}" height="540px" width="440px" class="img-responsive" alt="Work Process"/>
						<div class="what-agile-info">
							<h4>Redeployment</h4>
							<p>The contract stipulates that a trainee can be redeployed by the company if the need arises. However, once permanent employment has been achieved, the contract is terminated and that marks the end of a successful training.</p>
						</div>
					</div>
					<div class="col-md-6 what-grid1">
                        <div class="what-top1">
                            <div class="what-left">
                                <i class="glyphicon glyphicon-arrow-right" aria-hidden="true"></i>
                            </div>
                            <div class="what-right">
                                <h4>Interview</h4>
                                <p>the interested party is interviewed by our panel to understand exactly what they would like to benefit from.</p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
						<div class="what-top">
							<div class="what-left">
								<i class="glyphicon glyphicon-arrow-right" aria-hidden="true"></i>
							</div>
							<div class="what-right">
								<h4>Training</h4>
								<p>the house managers are trained on how to go on and about their jobs and how to handle the various scenarios they come across.</p>
							</div>
								<div class="clearfix"></div>
						</div>
						<div class="what-top1">
                            <div class="what-left">
                                <i class="glyphicon glyphicon-arrow-right" aria-hidden="true"></i>
                            </div>
							<div class="what-right">
								<h4>Vetting & On-boarding</h4>
								<p>the house managers are assessed based on what they’ve learned and this determines if they keep at it or not.</p>
							</div>
								<div class="clearfix"></div>
						</div>
                        <div class="what-top1">
                            <div class="what-left">
                                <i class="glyphicon glyphicon-arrow-right" aria-hidden="true"></i>
                            </div>
                            <div class="what-right">
                                <h4>On-the-job-training</h4>
                                <p>even after being placed to their various places of work, we continuously assess the work of our trainees to ensure they always perform to the standards that we have set.</p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
					</div>
						<div class="clearfix"></div>
				</div>
		</div>
	</div>
<!-- //work process -->
<!-- testimonials -->
{#	<div class="testimonials">#}
{#		<div class="container">#}
{#			<h3 class="w3ls_head"><span>Testim</span>onials</h3>#}
{#			<p class="w3agile"></p>#}
{#				#}
{#			<div class="w3ls_testimonials_grids">#}
{#				 <section class="center slider">#}
{#						<div class="agileits_testimonial_grid">#}
{#							<div class="w3l_testimonial_grid">#}
{#								<p>The house manager I hired is amazing. Kudos to you guys.</p>#}
{#								<h4>Miss Keysha</h4>#}
{#								<h5>Employer</h5>#}
{#								<div class="w3l_testimonial_grid_pos">#}
{#									<img src="{% static 'images/1.png' %}" alt=" " class="img-responsive" />#}
{#								</div>#}
{#							</div>#}
{#						</div>#}
{#						<div class="agileits_testimonial_grid">#}
{#							<div class="w3l_testimonial_grid">#}
{#								<p>I gained insightful knowledge that bettered me.</p>#}
{#								<h4>Laura Paul</h4>#}
{#								<h5>Student</h5>#}
{#								<div class="w3l_testimonial_grid_pos">#}
{#									<img src="{% static 'images/2.png' %}" alt=" " class="img-responsive" />#}
{#								</div>#}
{#							</div>#}
{#						</div>#}
{#						<div class="agileits_testimonial_grid">#}
{#							<div class="w3l_testimonial_grid">#}
{#								<p>We recruited their services when relocating to our new office premises. They did a splendid job.</p>#}
{#								<h4>Michael Doe</h4>#}
{#								<h5>Business man</h5>#}
{#								<div class="w3l_testimonial_grid_pos">#}
{#									<img src="{% static 'images/3.png' %}" alt=" " class="img-responsive" />#}
{#								</div>#}
{#							</div>#}
{#						</div>#}
{#				</section>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
<!-- //testimonials -->
{% endblock %}

employees/templates/Employees/navbar.html
{% block navbar %}
			<nav class="navbar navbar-default">
				<div class="navbar-header navbar-left">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<h3><a class="navbar-brand" href="{% url 'employees:home' %}"><i class="fa fa-mobile-phone" aria-hidden="true"></i>Dial For A <br>House Manager</a></h3>
				</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
					<nav class="link-effect-8" id="link-effect-8">
						<ul class="nav navbar-nav">
							<li class="active"><a href="/">Home</a></li>
							<li><a href="{% url 'employees:about' %}">About</a></li>
							<li><a href="{% url 'employees:employees' %}">Staff</a></li>
							<li><a href="{% url 'employees:gallery' %}">Gallery</a></li>
							<li><a href="{% url 'employees:contacts' %}">Contact</a></li>
						</ul>
					</nav>
				</div>
			</nav>
{% endblock %}